name: Create Pull Request

on:
  push:
    branches:
      - sathish1223-patch-1  # Define the source branch here

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4  # Use the version of the action that exists
      with:
        token: ${{ secrets.GH_PAT }}  # Use the secret you created
        title: "Pull request title"
        body: "Pull request description"
        branch: sathish1223-patch-1  # Source branch
        base: main  # Target branch
